name: CI/CD Pipeline
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [master]

jobs:
  test:
    name: Тестирование
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Run tests
        run: ./gradlew test --no-daemon

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    env:
      GHCR_USERNAME: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    outputs:
      app-version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get project version
        id: get-version
        run: |
          VERSION=$(grep 'version =' build.gradle.kts | awk -F\" '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Debug GHCR creds
        run: |
          echo "GHCR_USERNAME=$GHCR_USERNAME"
          echo "GHCR_TOKEN=${GHCR_TOKEN:0:4}••••"

      - name: Build and publish Docker image
        run: ./gradlew publishImage --no-daemon

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop haha-app || true
            docker rm haha-app || true
            docker run \
              -d \
              --name haha-app \
              -p 80:8080 \
              -e API_KEY="${{ secrets.API_KEY }}" \
              -e DNS_SERVER="${{ secrets.DNS_SERVER }}" \
              ghcr.io/greystekl0/haha:${{ needs.build-and-push.outputs.app-version }}